stages:
- name: docker-build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: markusressel/deinemudda:latest
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
