language: python
python:
  - "3.6"
  # currently not compatible with 3.7

services:
  - docker

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --system --deploy
  - pip install --no-cache-dir .

  # command to run tests
script:
  - cd tests
  - nosetests
  - cd ..

before_deploy:
  docker build -t markusressel/deinemudda .

deploy:
  - provider: script
    skip_cleanup: true
    script: bash travis/docker_push
    on:
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash travis/docker_push_latest
    on:
      branch: master
      tags: false