language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly" # currently points to 3.7-dev

services:
  - docker

before_install:
  docker build -t markusressel/deinemudda .
install:
  - pip install -r test_requirements.txt
# command to run tests
script:
  - nosetests

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
    tags: true