language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # currently not compatible with 3.7

services:
  - docker

before_install:
  docker build -t markusressel/deinemudda .
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
# command to run tests
script:
  - nosetests

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
    tags: true