"""Voting

Revision ID: 0e95c803b10d
Revises: cd9e7376fc77
Create Date: 2020-04-04 22:14:08.823574

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0e95c803b10d'
down_revision = 'cd9e7376fc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_rating',
                    sa.Column('rule_id', sa.String(), nullable=False),
                    sa.Column('response_text', sa.String(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('rule_id', 'response_text')
                    )
    op.create_table('vote_menus',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.Column('message_id', sa.Integer(), nullable=True),
                    sa.Column('rule_id', sa.String(), nullable=True),
                    sa.Column('message_text', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vote_menu_items',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('vote_menu_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['vote_menu_id'], ['vote_menus.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('vote_menu_id', 'id', name='_vote_menu_item_uc')
                    )
    op.create_table('vote_menu_item_voters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('vote_menu_item_id', sa.String(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['vote_menu_item_id'], ['vote_menu_items.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('vote_menu_item_id', 'user_id', name='_vote_menu_item_voter_uc')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_menu_item_voters')
    op.drop_table('vote_menu_items')
    op.drop_table('vote_menus')
    op.drop_table('response_rating')
    # ### end Alembic commands ###
