"""initial state

Revision ID: 44db4d5dc36e
Revises: 
Create Date: 2019-07-12 18:19:49.245944

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision = '44db4d5dc36e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from deinemudda.persistence.entity.chat import SettingsPickleType

    op.create_table('chats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('settings', SettingsPickleType(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association',
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
