"""primary keys must be strings instead of integers

Revision ID: bf2fd1c9ee8d
Revises: cd9e7376fc77
Create Date: 2022-03-28 01:28:58.998391

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import Integer

revision = 'bf2fd1c9ee8d'
down_revision = 'cd9e7376fc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop everything
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('association')
    op.drop_table('users')
    op.drop_table('chats')

    # recreate everything
    op.create_table('chats',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('is_banned', sa.Boolean(), nullable=True),
                    sa.Column('last_timeout', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association',
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    op.create_table('settings',
                    sa.Column('id', sa.BigInteger().with_variant(Integer, "sqlite"), nullable=False,
                              autoincrement=True),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('key', sa.String(), nullable=True),
                    sa.Column('value', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id', 'key', name='_setting_key_uc')
                    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop everything
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('association')
    op.drop_table('users')
    op.drop_table('chats')

    # recreate previous state
    op.create_table('chats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('is_banned', sa.Boolean(), nullable=True),
                    sa.Column('last_timeout', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association',
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    op.create_table('settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.Column('key', sa.String(), nullable=True),
                    sa.Column('value', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id', 'key', name='_setting_key_uc')
                    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    # ### end Alembic commands ###
